### ISSUE TITLE
Encrypted Text size

### ISSUE THREAD

**Issue by mtangoo** [loostro/cryptomute#10]
Where do I set the Length of Encrypted output? I cannot see it in the docs

**Comment by loostro** [comment]
Use [setValueRange](https://github.com/loostro/cryptomute#41-setvaluerangeminvalue-maxvalue) to set the minimum and maximum values.

**Comment by loostro** [comment]
You can also use DataConverter to pad left the output with zeroes.

**Comment by mtangoo** [comment]
>You can also use DataConverter to pad left the output with zeroes.
 
Can you explain this one?

**Comment by loostro** [comment]
You can use DataConverter class methods like:

[DataConverter::pad](https://github.com/loostro/cryptomute/blob/master/lib/Cryptomute/DataConverter.php#L211) to prepend number with zero'es to match given length.

Eg. `DataConverter::pad('123', 8)` will return `00000123`. Other methods also take optional 2nd argument `$length` and can pad the output.

**Comment by loostro** [comment]
Also the `encrypt` and `decrypt` methods take 3rd [$pad](https://github.com/loostro/cryptomute/blob/master/lib/Cryptomute/Cryptomute.php#L268) boolean argument (defaults to false) which will force the output to match maximum number's size.

Eg. if maximum number is 123456, then encrypt / decrypt with `$pad = true` will return 6 digits long string (if necessary - prepended with zeroes).

**Comment by mtangoo** [comment]
Thats what I wanted. Thank you.
It will benefit to explain that to readme

**Comment by Kaos-Industries** [comment]
> You can use DataConverter class methods like:
> 
> [DataConverter::pad](https://github.com/loostro/cryptomute/blob/master/lib/Cryptomute/DataConverter.php#L211) to prepend number with zero'es to match given length.
> 
> Eg. `DataConverter::pad('123', 8)` will return `00000123`. Other methods also take optional 2nd argument `$length` and can pad the output.

Will padding increase the collision rate of integers generated in a given range? Is a minimum range or length required to protect against this?

**Comment by ioleo** [comment]
Padding just makes sure your number follows a given format. There is no collision rate. Each number is uniquely mapped to another number within range. If its out of range it will be remapped until its within range.

Eg for 4-digit numbers it may look like:

in: 1000 -> out: 9452
in: 1001 -> map: 12012 -> out: 0010
in: 1002 -> map: 14200 -> map: 10001 -> out: 7231

On it should take 2 or less mappings to produce a number within range in most cases (there may be a few outliers that take 3 or more, but the library is very quick so you should not notice a diffrence).

**Comment by Kaos-Industries** [comment]
> Padding just makes sure your number follows a given format. There is no collision rate. Each number is uniquely mapped to another number within range. If its out of range it will be remapped until its within range.
> 
> Eg for 4-digit numbers it may look like:
> 
> in: 1000 -> out: 9452 in: 1001 -> map: 12012 -> out: 0010 in: 1002 -> map: 14200 -> map: 10001 -> out: 7231
> 
> It should take 2 or less mappings to produce a number within range in most cases (there may be a few outliers that take 3 or more, but the library is very quick so you should not notice a diffrence).

I just generated 50,000 records to test the package and it seems there's a bug with the padding function. I'm finding many generated IDs in my database that are shorter than 8 digits with no padding (some as short as 1 digit) even though my `$maxValue` is set to 99999999:

```
$cryptomute = new Cryptomute(
    'aes-192-ecb',      
    "16characterbasekey",  
    7,                 
    );

    $cryptomute->setValueRange(0, 99999999);  # 8 digits long
    $payment_id = $cryptomute->encrypt($transaction->id, 10, true);
```

I'm also surprised at how many of the generated numbers that are 8-digits are in the range 828xxxxx to 830xxxxx, although I have confirmed that out of 50,000 there's not a single duplicate.

**Comment by ioleo** [comment]
@Kaos-Industries you're welcome to send a PR or fork the project, I've since moved to another programming language, not really maintainig this anymore

**Comment by Kaos-Industries** [comment]
My bad, the problem must have been with my database constraints or something else, I tried generating the records again and the padding is now being applied.

**Comment by ioleo** [comment]
Good to hear! @Kaos-Industries

**Comment by mtangoo** [comment]
@ioleo may be you should archive this here and abandon on packagist pointing people to maintained fork
https://github.com/Teakowa/cryptomute
