### ISSUE TITLE
Error in Comparison

### ISSUE THREAD

**Issue by mtangoo** [loostro/cryptomute#11]
the line 
```php
        if (gmp_cmp($maxValue, $minValue) !== 1) {
            throw new InvalidArgumentException('Max value must be greater than min value.');
        }
```
keep called in my case making it hard for me to use it. The result of comparison in my case is 2 which is valid. The manual says of `gmp_cmp`

>Returns a positive value if a > b, zero if a = b and a negative value if a < b. 

So 2 is valid but you are checking for 1 only instead of positive numbers. Commenting out that one everything works great

**Comment by loostro** [comment]
Thanks for the report. I'll look into that and fix it today.

**Comment by loostro** [comment]
@mtangoo I've tagged a new release `v1.0.1` with fixes. Thanks for the report!

Also interesting side note: the previous code base run `> 10000` tests on random numbers, and it did pass, so it seems that **most of the time** `gmp_cmp` returns `-1` (for smaller), `0` (for equal), and `1` (for greater). Or maybe the tests are not working on numbers large enough. Anyways, it's fixed now! :)

**Comment by mtangoo** [comment]
Thanks for fixing. I will update with composer update
