### ISSUE TITLE
PHP 5.4 Compatibility

### ISSUE THREAD

**Issue by jan2000** [loostro/cryptomute#15]
The composer.json states that this nice library is compatible with PHP 5.4, however gmp_import and gmp_export functions are PHP 5 >= 5.6.1

The code below will fix this:

```php
if (!function_exists('gmp_import')) {
    function gmp_import($data)
    {
        return gmp_init(bin2hex($data), 16);
    }
}
if (!function_exists('gmp_export')) {
    function gmp_export($gmpnumber)
    {
        return hex2bin(gmp_strval($gmpnumber, 16));
    }
}
```

**Comment by loostro** [comment]
@jan2000 Thanks for report. I've updated `composer.json` to fix this overlooking of mine.
