### ISSUE TITLE
BCMath support

### ISSUE THREAD

**Issue by ConnorVG** [loostro/cryptomute#16]
GMP is sort of non-standard; even Google Cloud Platform's PHP runtime doesn't support it. Are there any plans to convert this to fallback to BCMath if GMP isn't available?

**Comment by loostro** [comment]
BCMath fallback was not planned, but you're welcome to submit a PR.

**Comment by ConnorVG** [comment]
I dropped interest in the implementation of a BCMath fallback after [this happened](https://github.com/GoogleCloudPlatform/php-docker/issues/303). Woo.

**Comment by loostro** [comment]
@ConnorVG great to hear :)
